const GET_GAMES = 'GET_GAMES'
const CREATE_GAME = 'CREATE_GAME'
const GET_DETAILS = 'GET_DETAILS'
const ERROR = 'ERROR'
const RESET_ERROR = 'RESET_ERROR'
const RESET_FILTERS = 'RESET_FILTERS'
const SORTING = 'SORTING'
const FILTER_BY_GENRE = 'FILTER_BY_GENRE'
const FILTER_BY_PLATFORM = 'FILTER_BY_PLATFORM'
const RESET_GAMES = 'RESET_GAMES'

export {GET_GAMES, GET_DETAILS, ERROR, RESET_ERROR,
     RESET_FILTERS, SORTING, FILTER_BY_GENRE,
    FILTER_BY_PLATFORM, CREATE_GAME, RESET_GAMES}